export const images = {
  logoWhite: "/images/white-logo.png",
  azureSmall: "/images/azure-icon-sm.png",
  corporateTrainings: "/images/corporate-trainings.png",
  courseActiveDirectory: "/images/course-active-directory.png",
  courseAzure: "/images/course-azure.png",
  courseExchange: "/images/course-exchange-server.png",
  courseNetworking: "/images/course-networking.png",
  courseOffice: "/images/course-office.png",
  courseWindows10: "/images/course-windows-10-edst.png",
  courseM365: "/images/course-m-365.png",
  heroImageLarge: "/images/hero-image-lg.png",
  logo: "/images/logo.png",
  office365Small: "/images/office-365-icon-sm.png",
  serverSmall: "/images/server-icon-sm.png",
  sliderImageOne: "/images/slider-image-1.png",
  sliderImageTwo: "/images/slider-image-2.png",
  heroRings: "/images/home-page/hero-rings.png",
  homePageRings: "/images/home-page/page-rings.png",
  rightConfetti: "/images/home-page/confetti-right.png",
  leftConfetti: "/images/home-page/confetti-left.png",
  patterns: "/images/home-page/patterns.png",
  brandsMonday: "/images/home-page/brands/monday.png",
  brandsMorpheus: "/images/home-page/brands/morpheus.png",
  brandsOracle: "/images/home-page/brands/oracle.png",
  brandsProtonet: "/images/home-page/brands/protonet.png",
  brandsSamsung: "/images/home-page/brands/samsung.png",
  brandsSegment: "/images/home-page/brands/segment.png",
  brandsZepplin: "/images/home-page/brands/zepplin.png",
  coursePageHeroBg: "/images/course-page/hero-bg.png",
  coursePageHeroImage: "/images/course-page/hero-image.png",
  awsLogo: "/images/course-page/aws-logo.png",
  gcpLogo: "/images/course-page/gcp-logo.png",
  windowsLogo: "/images/course-page/windows-logo.png",
  courseOutcome: "/images/course-page/course-outcome.png",
  azureAiHeroImage: "/images/course-page/azure-hero-image.png",
  azureAiHeroBg: "/images/course-page/azure-hero-bg.png",
  moduleIcon: "/images/course-page/module-icon.png",
  whiteRings: "/images/white-rings.png",
  batchesHero: "/images/batches/hero.png",
  corporateTrainingHero: "/images/corporate-training/hero.png",
  corporateTrainingBrands: "/images/corporate-training/brands.png",
  corporateTrainingBoyOnPc: "/images/corporate-training/boy-on-pc.png",
  corporateTrainingVodafone: "/images/corporate-training/vodafone.png",
  contact: {
    hero: "/images/contact/hero.png",
    map: "/images/contact/map.png",
    icons: {
      location: "/images/contact/icons/location.png",
      mail: "/images/contact/icons/mail.png",
      phone: "/images/contact/icons/phone.png",
    },
  },
  testimonials: {
    grids: {
      one: "/images/testimonials/grids/grid-img-1.png",
      two: "/images/testimonials/grids/grid-img-2.png",
      three: "/images/testimonials/grids/grid-img-3.png",
      four: "/images/testimonials/grids/grid-img-4.png",
      five: "/images/testimonials/grids/grid-img-5.png",
      six: "/images/testimonials/grids/grid-img-6.png",
      seven: "/images/testimonials/grids/grid-img-7.png",
    },
    rings: "/images/testimonials/rings.png",
    bar: "/images/testimonials/bar.png",
    brands: {
      colgate: "/images/testimonials/brands/colgate.png",
      johnson: "/images/testimonials/brands/johnson.png",
      capgemini: "/images/testimonials/brands/capgemini.png",
      concentrix: "/images/testimonials/brands/concentrix.png",
      placeholder: "/images/testimonials/brands/placeholder.png",
      tcs: "/images/testimonials/brands/tcs.png",
    },
  },
  about: {
    bg: "/images/about/bg.png",
    certificate: "/images/about/certificate.png",
    circle: "/images/about/circle.png",
    hero: "/images/about/hero.png",
    profile: "/images/about/profile.png",
    microsoft: "/images/about/microsoft.png",
    grids: {
      one: "/images/about/grid/grid-img-01.png",
      two: "/images/about/grid/grid-img-02.png",
      three: "/images/about/grid/grid-img-03.png",
      four: "/images/about/grid/grid-img-04.png",
      five: "/images/about/grid/grid-img-05.png",
      six: "/images/about/grid/grid-img-06.png",
    },
  },
  placement: {
    hero: "/images/placements/hero.png",
    side: "/images/placements/side.png",
    brands: {
      alcatel: "/images/placements/brands/alcatel.jpg",
      allied: "/images/placements/brands/allied.jpg",
      amazon: "/images/placements/brands/amazon.jpg",
      att: "/images/placements/brands/att.jpg",
      bharatPetroleum: "/images/placements/brands/bharat-petroleum.jpg",
      capgemini: "/images/placements/brands/capgemini.jpg",
      cisco: "/images/placements/brands/cisco.jpg",
      ciscoMeraki: "/images/placements/brands/cisco-meraki.jpg",
      cognizant: "/images/placements/brands/cognizant.jpg",
      continuum: "/images/placements/brands/continuum.jpg",
      dell: "/images/placements/brands/dell.jpg",
      digisol: "/images/placements/brands/digisol.jpg",
      ea: "/images/placements/brands/ea.jpg",
      ford: "/images/placements/brands/ford.jpg",
      ge: "/images/placements/brands/ge.jpg",
      google: "/images/placements/brands/google.jpg",
      googleCloud: "/images/placements/brands/google-cloud.jpg",
      gravitas: "/images/placements/brands/gravitas.jpg",
      hdfc: "/images/placements/brands/hdfc.jpg",
      hp: "/images/placements/brands/hp.jpg",
      ibm: "/images/placements/brands/ibm.jpg",
      icici: "/images/placements/brands/icici.jpg",
      iciciBank: "/images/placements/brands/icici-bank.jpg",
      igate: "/images/placements/brands/igate.jpg",
      infosys: "/images/placements/brands/infosys.jpg",
      intel: "/images/placements/brands/intel.jpg",
      ltInfotech: "/images/placements/brands/LT-Infotech.jpg",
      microland: "/images/placements/brands/microland.jpg",
      microsoft: "/images/placements/brands/microsoft.jpg",
      microsoftIndia: "/images/placements/brands/microsoft-india-gtsc.jpg",
      motorola: "/images/placements/brands/motorola.jpg",
      mphasis: "/images/placements/brands/mphasis.jpg",
      netmagic: "/images/placements/brands/netmagic.jpg",
      nomura: "/images/placements/brands/nomura.jpg",
      radisson: "/images/placements/brands/radisson.jpg",
      samsung: "/images/placements/brands/samsung.jpg",
      siemens: "/images/placements/brands/siemens.jpg",
      tcs: "/images/placements/brands/tcs.jpg",
      techMahindra: "/images/placements/brands/tech-Mahindra.jpg",
      verizon: "/images/placements/brands/verizon.jpg",
      videocon: "/images/placements/brands/videocon.jpg",
      vmware: "/images/placements/brands/vmware.jpg",
      vodafone: "/images/placements/brands/vodafone.jpg",
      wipro: "/images/placements/brands/wipro.jpg",
      yahoo: "/images/placements/brands/yahoo.jpg",
      abbott: "/images/placements/brands/abbott.jpg",
    },
    slides: [
      "/images/placements/slides/slides-01.png",
      "/images/placements/slides/slides-02.png",
      "/images/placements/slides/slides-03.png",
      "/images/placements/slides/slides-04.png",
      "/images/placements/slides/slides-05.png",
      "/images/placements/slides/slides-06.png",
      "/images/placements/slides/slides-07.png",
      "/images/placements/slides/slides-08.png",
      "/images/placements/slides/slides-09.png",
      "/images/placements/slides/slides-10.png",
      "/images/placements/slides/slides-11.png",
      "/images/placements/slides/slides-12.png",
      "/images/placements/slides/slides-13.png",
      "/images/placements/slides/slides-14.png",
      "/images/placements/slides/slides-15.png",
      "/images/placements/slides/slides-16.png",
    ],
  },
  training: {
    hero: "/images/training/hero.png",
    offer: "/images/training/offer.png",
    benefits: {
      one: "/images/training/benefits_one.png",
      two: "/images/training/benefits_two.png",
      three: "/images/training/benefits_three.png",
      four: "/images/training/benefits_four.png",
    },
    iconBenefit: "/images/training/icon_benefit.png",
    rings: {
      green: "images/training/green.png",
      orange: "images/training/orange.png",
      violet: "images/training/violet.png",
    },
    bg: "/images/training/bg.png",
    courses: {
      colgate: "/images/corporate-training/courses/Colgate.jpg",
      colgatePalmolive: "/images/corporate-training/courses/Colgate-Palmolive-Logo.png",
      continuum: "/images/corporate-training/courses/continuum.jpg",
      dia: "/images/corporate-training/courses/DIA.jpg",
      eclrete: "/images/corporate-training/courses/Eclrete.jpg",
      fini: "/images/corporate-training/courses/Fini.jpg",
      generalMills: "/images/corporate-training/courses/general-mills-india-pvt-ltd-sinnar-nashik-ready-mix-food-product-retailers-3j6w8ll.jpg",
      godrej: "/images/corporate-training/courses/godrej.jpg",
      tjuk: "/images/corporate-training/courses/tjuk.png",
      ittiam: "/images/corporate-training/courses/ittiam-systems-squarelogo-1389409335152.png",
      pspcl: "/images/corporate-training/courses/pspcl.jpg",
      lntInfotech: "/images/corporate-training/courses/LT-Infotech.jpg",
      lupin: "/images/corporate-training/courses/lupin.jpg",
      macleods: "/images/corporate-training/courses/macleods.jpg",
      netmagic: "/images/corporate-training/courses/Netmagic-Logo.png",
      oerlikon: "/images/corporate-training/courses/oerlikon.jpg",
      oginat: "/images/corporate-training/courses/oginat.jpg",
      rashtriya: "/images/corporate-training/courses/rashtriya-chemicals-and-fertilizers-squarelogo.png",
      reserve: "/images/corporate-training/courses/reserve.jpg",
      seclore: "/images/corporate-training/courses/seclore.jpg",
      sew: "/images/corporate-training/courses/SEW_LOGO.svg_.png",
      spectrum: "/images/corporate-training/courses/spectrum.jpg",
      surthland: "/images/corporate-training/courses/surthland.jpg",
      tata: "/images/corporate-training/courses/tata.jpg",
      techMahindra: "/images/corporate-training/courses/tech-Mahindra.jpg",
      accenture: "/images/corporate-training/courses/Accenture.jpg",
      bp: "/images/corporate-training/courses/bharat-petroleum.jpg",
      chenoa: "/images/corporate-training/courses/chenoa.jpg",
    }
  },
  course: {
    hero: "/images/course/hero.png",
    fundamentals: "/images/course/fundamentals.png",
    associate: "/images/course/associate.png",
    expert: "/images/course/experts.png",
    speciality: "/images/course/speciality.png",
  },
};
