export const images = {
  logoWhite: "/images/white-logo.webp",
  azureSmall: "/images/azure-icon-sm.webp",
  corporateTrainings: "/images/corporate-trainings.webp",
  courseActiveDirectory: "/images/course-active-directory.webp",
  courseAzure: "/images/course-azure.webp",
  courseExchange: "/images/course-exchange-server.webp",
  courseNetworking: "/images/course-networking.webp",
  courseOffice: "/images/course-office.webp",
  courseWindows10: "/images/course-windows-10-edst.webp",
  courseM365: "/images/course-m-365.webp",
  heroImageLarge: "/images/hero-image-lg.webp",
  logo: "/images/logo.webp",
  office365Small: "/images/office-365-icon-sm.webp",
  serverSmall: "/images/server-icon-sm.webp",
  sliderImageOne: "/images/slider-image-1.webp",
  sliderImageTwo: "/images/slider-image-2.webp",
  heroRings: "/images/home-page/hero-rings.webp",
  heroRingsSm: "/images/home-page/hero-rings-sm.webp",
  homePageRings: "/images/home-page/page-rings.webp",
  rightConfetti: "/images/home-page/confetti-right.webp",
  leftConfetti: "/images/home-page/confetti-left.webp",
  patterns: "/images/home-page/patterns.webp",
  brandsMonday: "/images/home-page/brands/monday.webp",
  brandsMorpheus: "/images/home-page/brands/morpheus.webp",
  brandsOracle: "/images/home-page/brands/oracle.webp",
  brandsProtonet: "/images/home-page/brands/protonet.webp",
  brandsSamsung: "/images/home-page/brands/samsung.webp",
  brandsSegment: "/images/home-page/brands/segment.webp",
  brandsZepplin: "/images/home-page/brands/zepplin.webp",
  coursePageHeroBg: "/images/course-page/hero-bg.webp",
  coursePageHeroImage: "/images/course-page/hero-image.webp",
  awsLogo: "/images/course-page/aws-logo.webp",
  gcpLogo: "/images/course-page/gcp-logo.webp",
  windowsLogo: "/images/course-page/windows-logo.webp",
  courseOutcome: "/images/course-page/course-outcome.webp",
  azureAiHeroImage: "/images/course-page/azure-hero-image.webp",
  azureAiHeroBg: "/images/course-page/azure-hero-bg.webp",
  moduleIcon: "/images/course-page/module-icon.webp",
  whiteRings: "/images/white-rings.webp",
  batchesHero: "/images/batches/hero.webp",
  corporateTrainingHero: "/images/corporate-training/hero.webp",
  corporateTrainingBrands: "/images/corporate-training/brands.webp",
  corporateTrainingBoyOnPc: "/images/corporate-training/boy-on-pc.webp",
  corporateTrainingVodafone: "/images/corporate-training/vodafone.webp",
  contact: {
    hero: "/images/contact/hero.webp",
    map: "/images/contact/map.webp",
    icons: {
      location: "/images/contact/icons/location.webp",
      mail: "/images/contact/icons/mail.webp",
      phone: "/images/contact/icons/phone.webp",
    },
  },
  testimonials: {
    grids: {
      one: "/images/testimonials/grids/grid-img-1.webp",
      two: "/images/testimonials/grids/grid-img-2.webp",
      three: "/images/testimonials/grids/grid-img-3.webp",
      four: "/images/testimonials/grids/grid-img-4.webp",
      five: "/images/testimonials/grids/grid-img-5.webp",
      six: "/images/testimonials/grids/grid-img-6.webp",
      seven: "/images/testimonials/grids/grid-img-7.webp",
    },
    rings: "/images/testimonials/rings.webp",
    bar: "/images/testimonials/bar.webp",
    brands: {
      colgate: "/images/testimonials/brands/colgate.webp",
      johnson: "/images/testimonials/brands/johnson.webp",
      capgemini: "/images/testimonials/brands/capgemini.webp",
      concentrix: "/images/testimonials/brands/concentrix.webp",
      placeholder: "/images/testimonials/brands/placeholder.webp",
      tcs: "/images/testimonials/brands/tcs.webp",
    },
  },
  about: {
    bg: "/images/about/bg.webp",
    certificate: "/images/about/certificate.webp",
    circle: "/images/about/circle.webp",
    hero: "/images/about/hero.webp",
    profile: "/images/about/profile.webp",
    microsoft: "/images/about/microsoft.webp",
    grids: {
      one: "/images/about/grid/grid-img-01.webp",
      two: "/images/about/grid/grid-img-02.webp",
      three: "/images/about/grid/grid-img-03.webp",
      four: "/images/about/grid/grid-img-04.webp",
      five: "/images/about/grid/grid-img-05.webp",
      six: "/images/about/grid/grid-img-06.webp",
    },
  },
  placement: {
    hero: "/images/placements/hero.webp",
    side: "/images/placements/side.webp",
    brands: {
      alcatel: "/images/placements/brands/alcatel.jpg",
      allied: "/images/placements/brands/allied.jpg",
      amazon: "/images/placements/brands/amazon.jpg",
      att: "/images/placements/brands/att.jpg",
      bharatPetroleum: "/images/placements/brands/bharat-petroleum.jpg",
      capgemini: "/images/placements/brands/capgemini.jpg",
      cisco: "/images/placements/brands/cisco.webp",
      ciscoMeraki: "/images/placements/brands/cisco-meraki.jpg",
      cognizant: "/images/placements/brands/cognizant.jpg",
      continuum: "/images/placements/brands/continuum.jpg",
      dell: "/images/placements/brands/dell.webp",
      digisol: "/images/placements/brands/digisol.jpg",
      ea: "/images/placements/brands/ea.jpg",
      ford: "/images/placements/brands/ford.webp",
      ge: "/images/placements/brands/ge.jpg",
      google: "/images/placements/brands/google.webp",
      googleCloud: "/images/placements/brands/google-cloud.jpg",
      gravitas: "/images/placements/brands/gravitas.jpg",
      hdfc: "/images/placements/brands/hdfc.jpg",
      hp: "/images/placements/brands/hp.jpg",
      ibm: "/images/placements/brands/ibm.jpg",
      // icici: "/images/placements/brands/icici.jpg",
      iciciBank: "/images/placements/brands/icici-bank.jpg",
      igate: "/images/placements/brands/igate.jpg",
      infosys: "/images/placements/brands/infosys.jpg",
      intel: "/images/placements/brands/intel.jpg",
      ltInfotech: "/images/placements/brands/LT-Infotech.jpg",
      microland: "/images/placements/brands/microland.jpg",
      microsoft: "/images/placements/brands/microsoft.jpg",
      microsoftIndia: "/images/placements/brands/microsoft-india-gtsc.jpg",
      motorola: "/images/placements/brands/motorola.jpg",
      mphasis: "/images/placements/brands/mphasis.jpg",
      netmagic: "/images/placements/brands/netmagic.jpg",
      nomura: "/images/placements/brands/nomura.jpg",
      radisson: "/images/placements/brands/radisson.jpg",
      samsung: "/images/placements/brands/samsung.jpg",
      siemens: "/images/placements/brands/siemens.jpg",
      tcs: "/images/placements/brands/tcs.jpg",
      techMahindra: "/images/placements/brands/tech-Mahindra.jpg",
      verizon: "/images/placements/brands/verizon.jpg",
      videocon: "/images/placements/brands/videocon.jpg",
      vmware: "/images/placements/brands/vmware.jpg",
      vodafone: "/images/placements/brands/vodafone.jpg",
      wipro: "/images/placements/brands/wipro.jpg",
      yahoo: "/images/placements/brands/yahoo.jpg",
      abbott: "/images/placements/brands/abbott.jpg",
      taj: "/images/placements/brands/taj_hotels.jpg",
      cvs: "/images/placements/brands/cvs_health.jpg",
      indianBank: "/images/placements/brands/indian_bank.jpg",
      hindustanUnilever: "/images/placements/brands/hindustan_uniliver.jpg"
    },
    slides: [
      "/images/placements/slides/slides-01.webp",
      "/images/placements/slides/slides-02.webp",
      "/images/placements/slides/slides-03.webp",
      "/images/placements/slides/slides-04.webp",
      "/images/placements/slides/slides-05.webp",
      "/images/placements/slides/slides-06.webp",
      "/images/placements/slides/slides-07.webp",
      "/images/placements/slides/slides-08.webp",
      "/images/placements/slides/slides-09.webp",
      "/images/placements/slides/slides-10.webp",
      "/images/placements/slides/slides-11.webp",
      "/images/placements/slides/slides-12.webp",
      "/images/placements/slides/slides-14.webp",
      "/images/placements/slides/slides-15.webp",
      "/images/placements/slides/slides-16.webp",
      "/images/placements/slides/slides-17.webp",
    ],
  },
  training: {
    hero: "/images/training/hero.webp",
    offer: "/images/training/offer.webp",
    benefits: {
      one: "/images/training/benefits_one.webp",
      two: "/images/training/benefits_two.webp",
      three: "/images/training/benefits_three.webp",
      four: "/images/training/benefits_four.webp",
    },
    iconBenefit: "/images/training/icon_benefit.webp",
    rings: {
      green: "images/training/green.webp",
      orange: "images/training/orange.webp",
      violet: "images/training/violet.webp",
    },
    bg: "/images/training/bg.webp",
    courses: {
      colgate: "/images/corporate-training/courses/Colgate.jpg",
      colgatePalmolive: "/images/corporate-training/courses/Colgate-Palmolive-Logo.webp",
      continuum: "/images/corporate-training/courses/continuum.jpg",
      dia: "/images/corporate-training/courses/DIA.jpg",
      eclrete: "/images/corporate-training/courses/Eclrete.jpg",
      fini: "/images/corporate-training/courses/Fini.jpg",
      generalMills: "/images/corporate-training/courses/general-mills-india-pvt-ltd-sinnar-nashik-ready-mix-food-product-retailers-3j6w8ll.jpg",
      godrej: "/images/corporate-training/courses/godrej.jpg",
      tjuk: "/images/corporate-training/courses/tjuk.webp",
      ittiam: "/images/corporate-training/courses/ittiam-systems-squarelogo-1389409335152.webp",
      pspcl: "/images/corporate-training/courses/pspcl.jpg",
      lntInfotech: "/images/corporate-training/courses/LT-Infotech.jpg",
      lupin: "/images/corporate-training/courses/lupin.jpg",
      macleods: "/images/corporate-training/courses/macleods.jpg",
      netmagic: "/images/corporate-training/courses/Netmagic-Logo.webp",
      oerlikon: "/images/corporate-training/courses/oerlikon.jpg",
      oginat: "/images/corporate-training/courses/oginat.jpg",
      rashtriya: "/images/corporate-training/courses/rashtriya-chemicals-and-fertilizers-squarelogo.webp",
      reserve: "/images/corporate-training/courses/reserve.jpg",
      seclore: "/images/corporate-training/courses/seclore.jpg",
      sew: "/images/corporate-training/courses/SEW_LOGO.svg_.webp",
      spectrum: "/images/corporate-training/courses/spectrum.jpg",
      surthland: "/images/corporate-training/courses/surthland.jpg",
      tata: "/images/corporate-training/courses/tata.jpg",
      techMahindra: "/images/corporate-training/courses/tech-Mahindra.jpg",
      accenture: "/images/corporate-training/courses/Accenture.jpg",
      bp: "/images/corporate-training/courses/bharat-petroleum.jpg",
      chenoa: "/images/corporate-training/courses/chenoa.jpg",
    }
  },
  course: {
    hero: "/images/course/hero.webp",
    fundamentals: "/images/course/fundamentals.webp",
    associate: "/images/course/associate.webp",
    expert: "/images/course/experts.webp",
    speciality: "/images/course/speciality.webp",
  },
};
